---
- name: install nginx
  hosts: web
  become: true

  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present

    - name: Ensure index.html is present
      copy:
        src: index.html
        dest: /var/www/html

    - name: Ensure nginx is running
      service:
        name: nginx.service
        state: started


- name: install db
  hosts: db
  become: true

  tasks:
    - name: Ensure postgresql package is present
      apt:
        name: postgresql
        state: present

    - name: Ensure postgres is running
      service:
        name: postgresql.service
        state: started
