---
- name: install nginx
  hosts: web
  become: true

  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present

    - name: Text change
      lineinfile:
        path: /var/www/html/index.nginx-debian.html
        regexp: 'Welcome to nginx'
        line: '<p><script> document.write(new Date().toLocaleDateString()); </script></p>'
