---
- name: install nginx
  hosts: web
  become: true

  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present

    # - name: Ensure SELinux is set to enforcing mode
    #   ansible.builtin.lineinfile:
    #     path: /var/www/index.html
    #     regexp: 'Hellp'
    #     line: SELINUX=enforcing


